import re

regexes = {
    "Slack Token": re.compile('(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})'),
    "RSA private key": re.compile('-----BEGIN RSA PRIVATE KEY-----'),
    "SSH (OPENSSH) private key": re.compile('-----BEGIN OPENSSH PRIVATE KEY-----'),
    "SSH (DSA) private key": re.compile('-----BEGIN DSA PRIVATE KEY-----'),
    "SSH (EC) private key": re.compile('-----BEGIN EC PRIVATE KEY-----'),
    "PGP private key block": re.compile('-----BEGIN PGP PRIVATE KEY BLOCK-----'),
    "Facebook Oauth": re.compile('[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*[\'|"][0-9a-f]{32}[\'|"]'),
    "Twitter Oauth": re.compile('[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[\'|"][0-9a-zA-Z]{35,44}[\'|"]'),
    "GitHub": re.compile('[g|G][i|I][t|T][h|H][u|U][b|B].*[[\'|"]0-9a-zA-Z]{35,40}[\'|"]'),
    "Google Oauth": re.compile('("client_secret":"[a-zA-Z0-9-_]{24}")'),
    "AWS API Key": re.compile('AKIA[0-9A-Z]{16}'),
    "Heroku API Key": re.compile('[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'),
    "Secret Key": re.compile('SECRET[\s\S]KEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|SECRETKEY[\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Generic Secret": re.compile('SECRET[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "API Key": re.compile('API[\s\S]KEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|APIKEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Sensitive Key": re.compile('SENSITIVE[\s\S]KEY[[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|SENSITIVEKEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Private Key": re.compile('PRIVATE[\s\S]KEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|PRIVATEKEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Access Key": re.compile('ACCESS[\s\S]KEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|ACCESSKEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "App Secret": re.compile('APP[\s\S]SECRET[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|APPSECRET[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Application Secret": re.compile('APPLICATION[\s\S]SECRET[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|APPLICATIONSECRET[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Application Key": re.compile('APPLICATION[\s\S]KEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|APPLICATIONKEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "App Key": re.compile('APP[\s\S]KEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|APPKEY[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Password": re.compile('PASSWORD[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "Passwd": re.compile('PASSWD[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "User": re.compile('USER[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "User Name": re.compile('USER[\s\S]NAME[\s|\S][\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|USERNAME[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
    "User ID": re.compile('USER[\s\S]ID[\s|\S][\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]|USERID[\s|\S][\s|\S][\s|\S][0-9a-zA-Z]{6,45}[\s|\S]', re.IGNORECASE),
}
